'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { create } from 'zustand';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, BrainCircuit, ChartCandlestick, Check, ChevronRight, FlaskConical, Gauge, LayoutDashboard, Menu, Radio, ShieldCheck, TrendingUp, X, Zap } from 'lucide-react';
import { DataTable, MetricCard, Panel, StatusBadge } from './ui';
import { MarketChart } from './market-chart';

export const sections=['command-center','trading','strategies','ai','experiments','risk'] as const;
export type Section=typeof sections[number];
export const isSection=(value:string):value is Section=>sections.includes(value as Section);
const config:Record<Section,{label:string;eyebrow:string;icon:typeof Activity}>={
  'command-center':{label:'Command Center',eyebrow:'Portfolio overview',icon:LayoutDashboard},trading:{label:'Trading',eyebrow:'Execution desk',icon:ChartCandlestick},strategies:{label:'Strategies',eyebrow:'Strategy engine',icon:TrendingUp},ai:{label:'AI',eyebrow:'Agent orchestration',icon:BrainCircuit},experiments:{label:'Experiments',eyebrow:'Research laboratory',icon:FlaskConical},risk:{label:'Risk',eyebrow:'Deterministic governor',icon:ShieldCheck},
};
const useShell=create<{mobile:boolean;halt:boolean;toggle:()=>void;openHalt:()=>void;closeHalt:()=>void}>(set=>({mobile:false,halt:false,toggle:()=>set(s=>({mobile:!s.mobile})),openHalt:()=>set({halt:true}),closeHalt:()=>set({halt:false})}));
const equity=[232,235,234,238,240,239,244,242,246,249,248,252,251,255,257,260,258,263,265,268,269,272];
const chartData=equity.map((value,i)=>({day:i+1,value}));
const pnlData=[{name:'Momentum',value:4860},{name:'Breakout',value:2740},{name:'Mean Revert',value:1260},{name:'Pairs',value:-580},{name:'Carry',value:920}];
const money=(v:string)=><span className={v.startsWith('+')?'profit':v.startsWith('−')||v.startsWith('-')?'loss':''}>{v}</span>;

function KillSwitch(){const {halt,closeHalt}=useShell();if(!halt)return null;return <div className="dialog-backdrop" role="presentation"><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="halt-title"><button className="dialog-close" onClick={closeHalt} aria-label="Close"><X size={17}/></button><span className="danger-symbol"><AlertTriangle size={22}/></span><p className="section-kicker danger">HIGH-IMPACT CONTROL</p><h2 id="halt-title">Halt all trading?</h2><p>This will cancel open orders, block new execution, and place every strategy in a safe stopped state. Positions will remain open.</p><label><input type="checkbox"/> I understand current positions are not closed automatically.</label><div className="dialog-actions"><button className="secondary-button" onClick={closeHalt}>Keep system armed</button><button className="danger-button">Confirm emergency halt</button></div></section></div>}

function Sidebar({section}:{section:Section}){const {mobile,toggle,openHalt}=useShell();return <aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="brand"><span className="brand-mark">K</span><span>Kairo</span><button className="nav-close" onClick={toggle}><X size={18}/></button></div><nav className="nav-list" aria-label="Primary navigation"><p className="nav-label">Workspace</p>{sections.map(id=>{const item=config[id],Icon=item.icon;return <Link onClick={()=>mobile&&toggle()} className={`nav-item ${section===id?'active':''}`} key={id} href={id==='command-center'?'/':`/${id}`}><Icon size={17}/><span>{item.label}</span>{section===id&&<ChevronRight className="nav-chevron" size={14}/>}</Link>})}</nav><div className="sidebar-foot"><div className="system-state"><span className="pulse"/><div><strong>System armed</strong><small>Paper environment</small></div></div><button className="halt-button" onClick={openHalt}><AlertTriangle size={16}/> EMERGENCY HALT</button></div></aside>}

function Topbar({section}:{section:Section}){const toggle=useShell(s=>s.toggle);return <header className="topbar"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={toggle}><Menu size={19}/></button><div><p className="eyebrow">Friday, August 28 · NYSE open</p><h1>{config[section].label}</h1></div><div className="topbar-actions"><span className="status-pill good"><Radio size={13}/> Live systems healthy</span><span className="clock">14:32:08 <small>UTC−5</small></span><button className="avatar" aria-label="Account menu">KA</button></div></header>}

function PageIntro({section,title,description,aside}:{section:Section;title:string;description:string;aside?:React.ReactNode}){return <div className="hero-row"><div><p className="section-kicker">{config[section].eyebrow}</p><h2>{title}</h2><p className="muted">{description}</p></div>{aside}</div>}

function EquityChart(){return <div className="simple-chart"><div className="chart-legend"><strong>$248.6K</strong><span>+$18,420 · 7.9%</span></div><ResponsiveContainer width="100%" height={230}><AreaChart data={chartData} margin={{top:20,right:0,left:-34,bottom:0}}><defs><linearGradient id="equity" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2563eb" stopOpacity=".2"/><stop offset="1" stopColor="#2563eb" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#eef1f5" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:9,fill:'#9aa3b1'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:9,fill:'#9aa3b1'}}/><Tooltip contentStyle={{border:'1px solid #e7eaf0',borderRadius:8,fontSize:10}}/><Area type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={2} fill="url(#equity)"/></AreaChart></ResponsiveContainer></div>}

function CommandCenter(){return <><PageIntro section="command-center" title="System operating within parameters" description="All automated strategies are synchronized. No action required." aside={<div className="regime"><span className="regime-icon"><Gauge size={17}/></span><div><small>MARKET REGIME</small><strong>Risk-on · Trending</strong></div><span className="confidence">87%</span></div>}/><div className="metric-grid"><MetricCard label="Account equity" value="$248,630.42" detail="+1.84% today" tone="good"/><MetricCard label="Today P&L" value="+$4,492.18" detail="Realized $2,804" tone="good"/><MetricCard label="Drawdown" value="−2.18%" detail="Limit −8.00%" tone="warning"/><MetricCard label="Capital at risk" value="$31,240" detail="12.6% of equity" tone="ai"/></div><div className="dashboard-grid"><Panel title="Equity curve" subtitle="30-day portfolio performance" action={<span className="mini-tabs"><b>1D</b><b>1W</b><b className="selected">1M</b><b>3M</b></span>}><EquityChart/></Panel><Panel title="System health" subtitle="Backend service status" action={<button className="text-button">Diagnostics</button>}><div className="health-list">{[['Broker connectivity','Alpaca Paper','18 ms','good'],['Market data','Polygon stream','42 ms','good'],['Risk governor','Deterministic','Authorized','good'],['AI orchestration','4 agents active','Nominal','ai']].map(([n,d,v,t])=><div className="health-row" key={n}><span className={`health-icon ${t==='ai'?'ai':''}`}>{t==='ai'?<BrainCircuit size={15}/>:<ShieldCheck size={15}/>}</span><div><strong>{n}</strong><small>{d}</small></div><span className={t==='ai'?'ai-text':'good-text'}>{v}</span></div>)}</div></Panel></div><div className="lower-grid"><Panel title="Open positions" subtitle="6 positions · $86,420 gross exposure"><DataTable headers={['Asset','Side','Strategy','Size','Mark','Unrealized P&L','Risk']} rows={[[<b>BTC / USD</b>,<StatusBadge tone="good">LONG</StatusBadge>,'Momentum v4','$28,460','$63,218',money('+$632.40'),<StatusBadge tone="good">Low</StatusBadge>],[<b>ETH / USD</b>,<StatusBadge tone="good">LONG</StatusBadge>,'Breakout α','$21,360','$3,506',money('+$550.11'),<StatusBadge tone="good">Low</StatusBadge>],[<b>SOL / USD</b>,<StatusBadge tone="danger">SHORT</StatusBadge>,'Mean Revert','$12,840','$148.60',money('+$224.18'),<StatusBadge tone="warning">Medium</StatusBadge>]]}/></Panel><Panel title="Decision & event feed" subtitle="Most recent first"><div className="event-feed">{[['14:31:48','Order filled','BTC long +0.18 @ 63,218','good'],['14:30:12','Risk check passed','Momentum v4 · score 0.86','good'],['14:28:02','Agent decision','ETH breakout confidence 78%','ai'],['14:22:41','Exposure warning','SOL sector allocation at 74%','warning']].map(([t,a,d,tone])=><div className="event" key={t}><span className={`event-dot ${tone}`}/><time>{t}</time><div><strong>{a}</strong><small>{d}</small></div></div>)}</div></Panel></div></>}

function Trading(){return <><PageIntro section="trading" title="BTC / USD execution desk" description="Paper broker · continuous market data · strategy-managed orders" aside={<div className="price-block"><small>BTC / USD</small><strong>$63,218.40</strong><span>+2.42%</span></div>}/><div className="trading-layout"><Panel title="BTC / USD" subtitle="1 hour candles · Polygon" action={<span className="mini-tabs"><b>1m</b><b>5m</b><b className="selected">1h</b><b>4h</b><b>1D</b></span>}><MarketChart/></Panel><div className="trading-side"><Panel title="Market status" subtitle="Live composite"><div className="market-stats"><div><span>Bid</span><b>$63,214.20</b></div><div><span>Ask</span><b>$63,219.10</b></div><div><span>Spread</span><b>0.78 bps</b></div><div><span>24h volume</span><b>$38.4B</b></div></div></Panel><Panel title="Position" subtitle="Momentum v4"><div className="position-card"><div><StatusBadge tone="good">LONG</StatusBadge><strong>0.450 BTC</strong></div><dl><dt>Average entry</dt><dd>$61,842.10</dd><dt>Unrealized P&L</dt><dd className="profit">+$619.34</dd><dt>Stop distance</dt><dd>2.4%</dd><dt>Risk allocation</dt><dd>3.1%</dd></dl><div className="progress"><i style={{width:'62%'}}/></div></div></Panel></div></div><Panel title="Execution ledger" subtitle="Orders and fills for the active session" action={<span className="mini-tabs"><b className="selected">All</b><b>Orders</b><b>Fills</b></span>}><DataTable headers={['Time','Symbol','Action','Type','Quantity','Price','Strategy','Status']} rows={[[<time>14:31:48</time>,<b>BTC/USD</b>,<StatusBadge tone="good">BUY</StatusBadge>,'Limit','0.180','$63,218.00','Momentum v4',<StatusBadge tone="good">Filled</StatusBadge>],[<time>14:16:03</time>,<b>ETH/USD</b>,<StatusBadge tone="good">BUY</StatusBadge>,'Market','2.400','$3,506.12','Breakout α',<StatusBadge tone="good">Filled</StatusBadge>],[<time>13:58:19</time>,<b>SOL/USD</b>,<StatusBadge tone="danger">SELL</StatusBadge>,'Stop','84.00','$147.42','Mean Revert',<StatusBadge tone="neutral">Open</StatusBadge>]]}/></Panel></>}

const strategies=[['Momentum v4','Trend following','Live','+$8,420','1.84','68%','good'],['Breakout α','Volatility expansion','Live','+$4,216','1.47','61%','good'],['Mean Revert','Statistical reversion','Shadow','+$1,806','1.21','58%','warning'],['Pairs Engine','Market neutral','Paused','−$580','0.82','44%','danger']];
function Strategies(){return <><PageIntro section="strategies" title="Strategy fleet" description="Deterministic execution modules governed by global portfolio risk." aside={<button className="primary-button">+ New strategy</button>}/><div className="metric-grid"><MetricCard label="Active strategies" value="6 / 8" detail="2 in shadow mode" tone="good"/><MetricCard label="Blended Sharpe" value="1.62" detail="+0.18 vs 30d" tone="good"/><MetricCard label="Total allocation" value="78.4%" detail="$194,940 deployed" tone="ai"/><MetricCard label="Session trades" value="42" detail="71.4% win rate" tone="good"/></div><div className="strategy-grid">{strategies.map(([name,type,status,pnl,sharpe,win,tone],i)=><article className="strategy-card" key={name}><div className="strategy-top"><span className={`strategy-icon s${i}`}><TrendingUp size={16}/></span><StatusBadge tone={tone as 'good'}>{status}</StatusBadge></div><h3>{name}</h3><p>{type}</p><div className="strategy-metrics"><div><span>30D P&L</span><b className={pnl.startsWith('−')?'loss':'profit'}>{pnl}</b></div><div><span>Sharpe</span><b>{sharpe}</b></div><div><span>Win rate</span><b>{win}</b></div></div><div className="allocation"><span>Capital allocation</span><b>{[26,22,14,8][i]}%</b></div><div className="progress"><i style={{width:`${[72,61,43,22][i]}%`}}/></div></article>)}</div><Panel title="Performance by strategy" subtitle="Net P&L · rolling 30 days"><div className="bar-chart"><ResponsiveContainer width="100%" height={260}><BarChart data={pnlData} margin={{top:20,right:18,left:-20,bottom:0}}><CartesianGrid stroke="#eef1f5" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize:9,fill:'#8d97a6'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:9,fill:'#8d97a6'}}/><Tooltip/><Bar dataKey="value" radius={[4,4,0,0]}>{pnlData.map((e,i)=><Cell key={i} fill={e.value>=0?'#2b73ea':'#e5484d'}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel></>}

function AgentGraph(){return <div className="agent-graph"><div className="graph-node market"><Radio size={15}/><b>Market</b><small>data</small></div><div className="graph-node agent n1"><BrainCircuit size={15}/><b>Signal</b><small>agent</small></div><div className="graph-node agent n2"><BrainCircuit size={15}/><b>Regime</b><small>agent</small></div><div className="graph-node agent n3"><BrainCircuit size={15}/><b>Critic</b><small>agent</small></div><div className="graph-node risk"><ShieldCheck size={15}/><b>Governor</b><small>risk</small></div><div className="graph-node exec"><Zap size={15}/><b>Execute</b><small>broker</small></div><span className="link l1"/><span className="link l2"/><span className="link l3"/><span className="link l4"/><span className="link l5"/></div>}
function AI(){return <><PageIntro section="ai" title="Agent decision system" description="Observe model activity, evidence flow, and deterministic approval boundaries." aside={<StatusBadge tone="ai">4 agents active</StatusBadge>}/><div className="metric-grid"><MetricCard label="Decisions today" value="184" detail="22 approved for execution" tone="ai"/><MetricCard label="Mean confidence" value="81.4%" detail="Threshold 72%" tone="good"/><MetricCard label="Risk vetoes" value="7" detail="3.8% of proposals" tone="warning"/><MetricCard label="Inference latency" value="742 ms" detail="p95 · nominal" tone="good"/></div><div className="ai-grid"><Panel title="Agent decision graph" subtitle="Current BTC momentum proposal"><AgentGraph/><div className="graph-caption"><span><i className="ai"/>AI inference</span><span><i className="good"/>deterministic approval</span><span><i/>data flow</span></div></Panel><Panel title="Current decision" subtitle="Proposal #D-240828-184"><div className="decision-card"><div className="decision-score"><span>Composite confidence</span><strong>86%</strong><div className="score-ring"><i/></div></div><div className="decision-action"><StatusBadge tone="good">AUTHORIZED</StatusBadge><h3>Increase BTC long</h3><p>+0.18 BTC · limit $63,218</p></div><div className="evidence-list"><p><Check size={13}/> Momentum alignment <b>0.91</b></p><p><Check size={13}/> Regime compatibility <b>0.84</b></p><p><Check size={13}/> Portfolio risk check <b>Pass</b></p><p><Check size={13}/> Broker preflight <b>Pass</b></p></div></div></Panel></div><Panel title="Agent activity" subtitle="Traceable decision timeline"><DataTable headers={['Time','Agent','Task','Output','Confidence','Latency','State']} rows={[[<time>14:31:46</time>,'Risk critic','Validate BTC proposal','Approve','94%','118 ms',<StatusBadge tone="good">Complete</StatusBadge>],[<time>14:31:44</time>,'Signal agent','Momentum synthesis','Long +0.18','86%','402 ms',<StatusBadge tone="ai">Complete</StatusBadge>],[<time>14:31:41</time>,'Regime agent','Classify market','Risk-on trend','88%','222 ms',<StatusBadge tone="ai">Complete</StatusBadge>]]}/></Panel></>}

function Experiments(){return <><PageIntro section="experiments" title="Research experiments" description="Promote strategies only after reproducible evidence and risk review." aside={<button className="primary-button">+ New experiment</button>}/><div className="scorecard"><MetricCard label="Running" value="4" detail="36 allocated workers" tone="ai"/><MetricCard label="Awaiting review" value="3" detail="Evidence complete" tone="warning"/><MetricCard label="Promoted this month" value="2" detail="Into shadow mode" tone="good"/><MetricCard label="Compute budget" value="64%" detail="$128 remaining" tone="neutral"/></div><div className="experiment-grid"><Panel title="Experiment scorecard" subtitle="EXP-042 · Adaptive breakout filters"><div className="score-body"><div className="big-score"><span>Promotion score</span><strong>82.4</strong><small>Candidate threshold 78.0</small></div><div className="score-bars">{[['Out-of-sample Sharpe',88],['Drawdown resilience',79],['Regime stability',84],['Execution realism',76]].map(([n,v])=><div key={n as string}><p><span>{n}</span><b>{v}</b></p><div className="progress"><i style={{width:`${v}%`}}/></div></div>)}</div></div></Panel><Panel title="Research guardrails" subtitle="Promotion requirements"><div className="checklist">{[['Walk-forward validation','Passed','good'],['Minimum 500 trades','1,842 trades','good'],['Monte Carlo stability','Passed','good'],['Overfit probability','12.4%','good'],['Risk owner review','Pending','warning']].map(([n,v,t])=><div key={n}><span className={`check ${t}`}><Check size={12}/></span><strong>{n}</strong><em className={t}>{v}</em></div>)}</div></Panel></div><Panel title="Experiment registry" subtitle="Static research catalog"><DataTable headers={['ID','Hypothesis','Owner','Stage','Sharpe','Max DD','Last run']} rows={[[<b>EXP-042</b>,'Adaptive breakout filters','Research agent',<StatusBadge tone="warning">Review</StatusBadge>,'1.86','−6.2%','14:08'],[<b>EXP-041</b>,'Funding-rate carry ensemble','Quant agent',<StatusBadge tone="ai">Running</StatusBadge>,'—','—','13:42'],[<b>EXP-039</b>,'Regime-aware position sizing','Risk agent',<StatusBadge tone="good">Shadow</StatusBadge>,'1.63','−4.8%','Yesterday'],[<b>EXP-036</b>,'ETH/BTC residual mean reversion','Quant agent',<StatusBadge tone="danger">Rejected</StatusBadge>,'0.74','−12.1%','Aug 24']]}/></Panel></>}

function Risk(){return <><PageIntro section="risk" title="Portfolio risk governor" description="Hard deterministic constraints remain authoritative over every strategy and agent." aside={<StatusBadge tone="good">Governor authorized</StatusBadge>}/><div className="metric-grid"><MetricCard label="Portfolio heat" value="12.6%" detail="Limit 22.0%" tone="good"/><MetricCard label="Gross exposure" value="$146,280" detail="58.8% of equity" tone="ai"/><MetricCard label="Daily loss buffer" value="$13,940" detail="79% remaining" tone="good"/><MetricCard label="Active warnings" value="1" detail="SOL concentration" tone="warning"/></div><div className="risk-grid"><Panel title="Risk utilization" subtitle="Current value against hard limit"><div className="limits">{[['Daily loss','21%','$3,720 / $17,660','good'],['Portfolio heat','57%','12.6% / 22.0%','good'],['Gross exposure','74%','58.8% / 80.0%','warning'],['Single asset','62%','12.4% / 20.0%','good'],['Correlated cluster','81%','28.4% / 35.0%','warning']].map(([n,w,v,t])=><div className="limit-row" key={n}><div><strong>{n}</strong><span>{v}</span></div><div className="progress"><i className={t} style={{width:w}}/></div><b>{w}</b></div>)}</div></Panel><Panel title="Exposure by asset" subtitle="Net portfolio allocation"><div className="exposure-list">{[['BTC',28.4,'$70,612'],['ETH',18.2,'$45,250'],['SOL',8.6,'$21,380'],['Other',3.6,'$8,952']].map(([n,v,m],i)=><div key={n as string}><span className={`coin c${i}`}>{(n as string)[0]}</span><strong>{n}</strong><div className="progress"><i style={{width:`${Number(v)*2.7}%`}}/></div><b>{v}%</b><small>{m}</small></div>)}</div></Panel></div><Panel title="Risk events" subtitle="Governor decisions and threshold activity"><DataTable headers={['Time','Severity','Rule','Source','Decision','Context']} rows={[[<time>14:22:41</time>,<StatusBadge tone="warning">Warning</StatusBadge>,'Correlated cluster limit','SOL Mean Revert','Size reduced','Proposed 112 SOL → approved 84'],[<time>13:48:10</time>,<StatusBadge tone="good">Info</StatusBadge>,'Pre-trade risk check','BTC Momentum','Authorized','Portfolio heat after fill: 12.6%'],[<time>12:16:08</time>,<StatusBadge tone="danger">Blocked</StatusBadge>,'Daily turnover cap','Scalper v2','Rejected','Strategy turnover exceeded 3.0×']]} /></Panel></>}

export function DashboardApp({section}:{section:Section}){const path=usePathname();return <div className="app-shell"><Sidebar section={section}/><main className="workspace"><Topbar section={section}/><section className="content" key={path}>{section==='command-center'?<CommandCenter/>:section==='trading'?<Trading/>:section==='strategies'?<Strategies/>:section==='ai'?<AI/>:section==='experiments'?<Experiments/>:<Risk/>}</section></main><KillSwitch/></div>}
